import { Pharmacy, UserRole, VerificationStatus } from "@/types";

export const mockPharmacies: Pharmacy[] = [
  {
    id: "pharm1",
    email: "contact@apollopharmacy.in",
    phone: "+91 40 2345 6789",
    role: UserRole.PHARMACY,
    full_name: "Apollo Pharmacy Store Managers",
    avatar_url: "https://lh3.googleusercontent.com/aida-public/AB6AXuDcAFIy8qO6brIXU26lUqZ8yEvPoM3sjOsaPdIOcouQJF50FK6ukCCpcGQEmXFhYQnq5CcpJDapkCp8hElmtvDhMavZiT5Dy115WoH3468LR2c_EtDblF5OdQQnP1mUubCESQqQsJuya7VuoajPt5OJFSnk4XXf1kfn5UWwu1Wz8-1QwGesZmZWamiD1tEboBoKDTTkJA8A9ECFuw9DOGg8ZxVN1oLk9ecQ6crjfe4n3RLPxcM4-y_J",
    created_at: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true,
    pharmacy_name: "Apollo Pharmacy",
    license_number: "DL-HYD-2023-9988",
    license_expiry: "2028-12-31",
    gst_number: "36AAAAA1111A1Z1",
    address: "Road No 36, Jubilee Hills",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500033",
    verification_status: VerificationStatus.APPROVED,
    rating: 4.8,
    total_bids: 412,
    successful_bids: 289,
    response_time_avg: "8 minutes",
    established_year: 2011,
  },
  {
    id: "pharm2",
    email: "info@medplusindia.com",
    phone: "+91 40 4444 8888",
    role: UserRole.PHARMACY,
    full_name: "MedPlus Store Manager",
    avatar_url: null,
    created_at: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true,
    pharmacy_name: "MedPlus Pharmacy",
    license_number: "DL-HYD-2024-4455",
    license_expiry: "2029-06-30",
    gst_number: "36BBBBB2222B2Z2",
    address: "Madhapur Main Road",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500081",
    verification_status: VerificationStatus.APPROVED,
    rating: 4.6,
    total_bids: 350,
    successful_bids: 210,
    response_time_avg: "12 minutes",
    established_year: 2015,
  },
  {
    id: "pharm3",
    email: "contact@netmeds.com",
    phone: "+91 44 6677 8899",
    role: UserRole.PHARMACY,
    full_name: "Netmeds Logistics Manager",
    avatar_url: null,
    created_at: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true,
    pharmacy_name: "Netmeds Store",
    license_number: "DL-MAS-2023-3322",
    license_expiry: "2028-09-15",
    gst_number: "33CCCCC3333C3Z3",
    address: "Kondapur Cross Roads",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500084",
    verification_status: VerificationStatus.APPROVED,
    rating: 4.5,
    total_bids: 280,
    successful_bids: 180,
    response_time_avg: "15 minutes",
    established_year: 2018,
  },
  {
    id: "pharm4",
    email: "admin@wellnessforever.com",
    phone: "+91 22 8888 9999",
    role: UserRole.PHARMACY,
    full_name: "Wellness Manager",
    avatar_url: null,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    is_active: false,
    pharmacy_name: "Wellness Forever",
    license_number: "DL-BOM-2026-1122",
    license_expiry: "2031-03-20",
    gst_number: "27DDDDD4444D4Z4",
    address: "Hitech City Boulevard",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500081",
    verification_status: VerificationStatus.PENDING,
    rating: 0,
    total_bids: 0,
    successful_bids: 0,
    response_time_avg: "—",
    established_year: 2023,
  }
];
