import { authRepositoryMock } from "./auth.repository.mock";
import { authRepositoryFirebase } from "./auth.repository.firebase";
import { userRepositoryMock } from "./user.repository.mock";
import { userRepositoryFirebase } from "./user.repository.firebase";
import { patientRepositoryMock } from "./patient.repository.mock";
import { patientRepositoryFirebase } from "./patient.repository.firebase";
import { pharmacyRepositoryMock } from "./pharmacy.repository.mock";
import { pharmacyRepositoryFirebase } from "./pharmacy.repository.firebase";
import { prescriptionRepositoryMock } from "./prescription.repository.mock";
import { prescriptionRepositoryFirebase } from "./prescription.repository.firebase";
import { auctionRepositoryMock } from "./auction.repository.mock";
import { auctionRepositoryFirebase } from "./auction.repository.firebase";
import { bidRepositoryMock } from "./bid.repository.mock";
import { bidRepositoryFirebase } from "./bid.repository.firebase";
import { offerRepositoryMock } from "./offer.repository.mock";
import { offerRepositoryFirebase } from "./offer.repository.firebase";
import { reservationRepositoryMock } from "./reservation.repository.mock";
import { reservationRepositoryFirebase } from "./reservation.repository.firebase";
import { notificationRepositoryMock } from "./notification.repository.mock";
import { notificationRepositoryFirebase } from "./notification.repository.firebase";
import { adminRepositoryMock } from "./admin.repository.mock";
import { adminRepositoryFirebase } from "./admin.repository.firebase";
import { settingsRepositoryMock } from "./settings.repository.mock";
import { settingsRepositoryFirebase } from "./settings.repository.firebase";
import { auctionEngineRepositoryMock } from "./auction-engine.repository.mock";
import { auctionEngineRepositoryFirebase } from "./auction-engine.repository.firebase";
import { verificationRepositoryMock } from "./verification.repository.mock";
import { verificationRepositoryFirebase } from "./verification.repository.firebase";
import { moderationRepositoryMock } from "./moderation.repository.mock";
import { moderationRepositoryFirebase } from "./moderation.repository.firebase";
import { auditRepositoryMock } from "./audit.repository.mock";
import { auditRepositoryFirebase } from "./audit.repository.firebase";
import { analyticsRepositoryMock } from "./analytics.repository.mock";
import { analyticsRepositoryFirebase } from "./analytics.repository.firebase";
import { notificationPreferenceRepositoryMock } from "./notification-preference.repository.mock";
import { notificationPreferenceRepositoryFirebase } from "./notification-preference.repository.firebase";
import { deviceTokenRepositoryMock } from "./device-token.repository.mock";
import { deviceTokenRepositoryFirebase } from "./device-token.repository.firebase";

const useFirebase = process.env.NEXT_PUBLIC_USE_FIREBASE === "firebase";

export const authRepository = useFirebase ? authRepositoryFirebase : authRepositoryMock;
export const userRepository = useFirebase ? userRepositoryFirebase : userRepositoryMock;
export const patientRepository = useFirebase ? patientRepositoryFirebase : patientRepositoryMock;
export const pharmacyRepository = useFirebase ? pharmacyRepositoryFirebase : pharmacyRepositoryMock;
export const prescriptionRepository = useFirebase ? prescriptionRepositoryFirebase : prescriptionRepositoryMock;
export const auctionRepository = useFirebase ? auctionRepositoryFirebase : auctionRepositoryMock;
export const bidRepository = useFirebase ? bidRepositoryFirebase : bidRepositoryMock;
export const offerRepository = useFirebase ? offerRepositoryFirebase : offerRepositoryMock;
export const reservationRepository = useFirebase ? reservationRepositoryFirebase : reservationRepositoryMock;
export const notificationRepository = useFirebase ? notificationRepositoryFirebase : notificationRepositoryMock;
export const adminRepository = useFirebase ? adminRepositoryFirebase : adminRepositoryMock;
export const settingsRepository = useFirebase ? settingsRepositoryFirebase : settingsRepositoryMock;
export const auctionEngineRepository = useFirebase ? auctionEngineRepositoryFirebase : auctionEngineRepositoryMock;
export const verificationRepository = useFirebase ? verificationRepositoryFirebase : verificationRepositoryMock;
export const moderationRepository = useFirebase ? moderationRepositoryFirebase : moderationRepositoryMock;
export const auditRepository = useFirebase ? auditRepositoryFirebase : auditRepositoryMock;
export const analyticsRepository = useFirebase ? analyticsRepositoryFirebase : analyticsRepositoryMock;
export const notificationPreferenceRepository = useFirebase ? notificationPreferenceRepositoryFirebase : notificationPreferenceRepositoryMock;
export const deviceTokenRepository = useFirebase ? deviceTokenRepositoryFirebase : deviceTokenRepositoryMock;

// Re-export interfaces for typing elsewhere if needed
export * from "./interfaces/auth.repository";
export * from "./interfaces/user.repository";
export * from "./interfaces/patient.repository";
export * from "./interfaces/pharmacy.repository";
export * from "./interfaces/prescription.repository";
export * from "./interfaces/auction.repository";
export * from "./interfaces/bid.repository";
export * from "./interfaces/offer.repository";
export * from "./interfaces/reservation.repository";
export * from "./interfaces/notification.repository";
export * from "./interfaces/admin.repository";
export * from "./interfaces/settings.repository";
export * from "./interfaces/auction-engine.repository";
export * from "./interfaces/verification.repository";
export * from "./interfaces/moderation.repository";
export * from "./interfaces/audit.repository";
export * from "./interfaces/analytics.repository";
export * from "@/features/notification-engine/notification-engine.repository";
